on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.
  workflow_dispatch:

permissions: {}

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Manual from Stable Channel
        run: |
          nix build \
            --impure \
            --out-link result-nixos-manual-stable \
            --print-build-logs \
            --expr '
              let
                pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/nixos-stable.tar.gz") {};
              in
                pkgs.nixos-manual.manualHTML
            '

      - name: Build Manual from Unstable Channel
        run: |
          nix build \
            --impure \
            --out-link result-nixos-manual-unstable \
            --print-build-logs \
            --expr '
              let
                pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz") {};
              in
                pkgs.nixos-manual.manualHTML
            '

      - name: Copy Outputs to Public Directory
        run: |
          mkdir --parents public/nixos/stable public/nixos/unstable
          cp --recursive --dereference result-nixos-manual-stable/share/doc/nixos/* public/nixos/stable/
          cp --recursive --dereference result-nixos-manual-unstable/share/doc/nixos/* public/nixos/unstable/
          # Jekyll is designed to ignore any files or folders that start with an underscore (_) or a dot (.) character.
          # Do not use Jekyll to process these files. Just serve them exactly as they are.
          touch public/.nojekyll

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: public/

      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
