on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday.
  workflow_dispatch:

permissions: {}

concurrency:
  group: "deploy-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel:
          - name: stable
            branch: nixos-25.11
          - name: unstable
            branch: nixos-unstable
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Manual
        run: |
          nix build \
            --impure \
            --out-link result \
            --print-build-logs \
            --expr '
              let
                pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/${{ matrix.channel.branch }}.tar.gz") {};
                nixos = import (pkgs.path + "/nixos/lib/eval-config.nix") {
                  modules = [ ];
                };
              in
                nixos.config.system.build.manual.manualHTML
            '

      - name: Prepare Artifact
        run: |
          mkdir --parents artifact/${{ matrix.channel.name }}
          cp --recursive result/share/doc/nixos/* artifact/${{ matrix.channel.name }}/

      - uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.3
        with:
          name: manual-${{ matrix.channel.name }}
          path: artifact/${{ matrix.channel.name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: manual-stable
          path: public/nixos/stable

      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: manual-unstable
          path: public/nixos/unstable

      - name: Bypass Jekyll Processing
        run: |
          touch public/.nojekyll

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: public/

      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
